/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CapacitySnapshots {
  allocatedDays: number | null;
  availableDays: number | null;
  id: Generated<number>;
  notes: string | null;
  ptoAdjustments: Generated<number | null>;
  quarterId: string;
  snapshotDate: Generated<Timestamp | null>;
  sprintId: string | null;
  teamId: string;
  totalCapacityDays: number | null;
}

export interface Holidays {
  description: string | null;
  holidayDate: Timestamp;
  id: Generated<number>;
  quarterId: string;
}

export interface Projects {
  createdAt: Generated<Timestamp | null>;
  dependencies: string | null;
  displayOrder: Generated<number | null>;
  hasFrm: Generated<boolean | null>;
  id: string;
  internalTimeline: Timestamp | null;
  linearIssueId: string;
  notes: string | null;
  plannedWeeks: Generated<number | null>;
  quarterId: string;
  teamId: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface PtoEntries {
  createdAt: Generated<Timestamp | null>;
  daysCount: number;
  endDate: Timestamp;
  engineerName: string;
  id: Generated<number>;
  notes: string | null;
  quarterId: string;
  startDate: Timestamp;
  teamId: string;
}

export interface Quarters {
  createdAt: Generated<Timestamp | null>;
  endDate: Timestamp;
  id: string;
  meetingTimePercentage: Generated<number | null>;
  name: string;
  ptoDaysPerEngineer: Generated<number | null>;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp | null>;
  workDaysPerWeek: Generated<number | null>;
}

export interface SprintAllocations {
  actualDays: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  engineersAssigned: string | null;
  id: Generated<number>;
  isManualOverride: Generated<boolean | null>;
  numEngineers: Generated<number | null>;
  phase: Generated<string | null>;
  plannedDays: Generated<number | null>;
  plannedDescription: string | null;
  projectId: string;
  sprintGoal: string | null;
  sprintId: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Sprints {
  createdAt: Generated<Timestamp | null>;
  endDate: Timestamp;
  id: string;
  name: string;
  quarterId: string;
  sprintNumber: number;
  startDate: Timestamp;
}

export interface SprintSnapshots {
  createdBy: string | null;
  id: Generated<number>;
  notes: string | null;
  snapshotData: string;
  snapshotDate: Generated<Timestamp | null>;
  sprintId: string;
}

export interface TeamQuarterSettings {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  ktloEngineers: Generated<number | null>;
  meetingTimePercentage: Generated<number | null>;
  ptoDaysPerEngineer: Generated<number | null>;
  quarterId: string;
  teamId: string;
  totalEngineers: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Teams {
  createdAt: Generated<Timestamp | null>;
  id: string;
  ktloEngineers: Generated<number | null>;
  linearTeamId: string | null;
  name: string;
  ptoDaysPerEngineer: Generated<number | null>;
  totalEngineers: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  capacitySnapshots: CapacitySnapshots;
  holidays: Holidays;
  projects: Projects;
  ptoEntries: PtoEntries;
  quarters: Quarters;
  sprintAllocations: SprintAllocations;
  sprints: Sprints;
  sprintSnapshots: SprintSnapshots;
  teamQuarterSettings: TeamQuarterSettings;
  teams: Teams;
}
